name: check-base-branch
permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce PRs to main must come from release branches
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          if [[ "$HEAD_REF" != release/* ]]; then
            echo "‚ùå PRs to main must come from 'release/*' branches, not '$HEAD_REF'."
            exit 1
          fi
